### ISSUE TITLE
The command "scss --no-cache --update ./App.scss:./wwwroot/css/App.css" exited with code 9009

### ISSUE THREAD

**Issue by sth349** [bmsantos/bionic#2]
I have installed bionic v1.0.18, sass trough npm and "dotnet --version" returns "2.1.300" but I do have some newer versions of dotnet installed as well but when I try do execute bionic serve I get this message:
```
C:\Users\User\Videos\BlazorTesting\BlazorApp\BlazorApp.csproj(25,9): error MSB3073: The command "scss --no-cache --update ./App.scss:./wwwroot/css/App.css" exited with code 9009.

The build failed. Please fix the build errors and run again.
watch : Exited with error code 1
```

**Comment by bmsantos** [comment]
@sth349, I've recently learned that SASS actually offers two different versions of SASS installers. An older one based on Ruby and a newer one. The newer version does not offer the ```scss``` command or the ```--no-cache``` option.

My guess is that you have the non-Ruby version installed. Can you edit your project ```.csproj``` file and replace:

```xml
        <Exec Command="scss --no-cache --update ./App.scss:./wwwroot/css/App.css" />
```

With:

```xml
      <Exec Command="sass --update ./App.scss:./wwwroot/css/App.css" />
```

Also, if you are on Windows, please make sure you have ```nuget.exe``` installed and availlable in the PATH.

More on that here: https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools
